environment:
  matrix:
    - nodejs_version: "4.4.4"
      platform: x64
      configuration: Release
      msvs_toolset: 14
      TOOLSET_ARGS: --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140

install:
  - cmd: git submodule update --init
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) x64
  - npm config set msvs_version 2015 --global
  - npm config set target_arch x64 --global
  - npm install -g node-gyp

build_script:
  - npm install

test_script:
  - npm test

