install:
  - cmd: git submodule update --init
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm config set msvs_version 2015 --global
  - npm config set target_arch x64 --global
  - npm install -g node-gyp
  - npm install --release

test_script:
  - npm test

environment:
  matrix:
    - nodejs_version: "4.4.4"
