
environment:
  matrix:
    - nodejs_version: 0.10.40
      platform: x64
      configuration: Release
      msvs_toolset: 12
      TOOLSET_ARGS: --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140

install:
  - CALL scripts\build-appveyor.bat

build: off
test: off
deploy: off
